#!/usr/bin/env bash
##Modifies host file
cp /etc/hosts /tmp/hosts.new
echo '127.0.0.2		localhost' > /tmp/hosts.new
echo '8.8.8.8		facebook.com' >> /tmp/hosts.new
cp -f ~/tmp/hosts.new /etc/hosts
rm /tmp/hosts.new

