#!/usr/bin/env bash
#Script to configure the ssh configuration file
cat <<EOF >> ~/.ssh/config
Host myserver
    HostName 98.98.98.98
    User ubuntu
    IdentityFile ~/.ssh/school
    PasswordAuthentication no
EOF
